server:
  port: 8081

spring:
  application:
    name: stock-service
  data:
    rest:
      basePath: /stock-service/api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka